name: Deploy Infrastructure by Bicep

on:
  workflow_dispatch:

jobs:
  what_if:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS  }}
      - name: what-if
        run: |
          az deployment sub what-if \
            --location westeurope \
            --template-file ./main.bicep

  deployrg:
    needs: what_if
    environment: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS  }}
      - name: Deployment ResourceGroup
        run: |
          az deployment sub create \
            --location westeurope \
            --template-file ./main.bicep

  deploysqlserver:
    needs: deployrg
    environment: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS  }}
      - name: Deployment SQL Server and Database
        run: az deployment group what-if --mode Incremental --name rollout01 --resource-group 'rg_dev_infrastruktur' --template-file ./db2.bicep
